language: python
sudo: required
matrix:
  include:
  - env: TARGET=pep8
  - env: TARGET=py2
  - env: TARGET=py3
  allow_failures:
  - env: TARGET=pep8
script:
- true
install:
- docker build . -t ${TARGET} -f .travis/${TARGET}.docker
deploy:
  provider: pypi
  user: lerato
  password:
    secure: cvCby8jS1bUxl6koXI13HUdg4epD11KPOJp4Smy+NopOZAeIcoOtEqcSvu5GA7cgMOMhUnOrng1CSSi3ulxRvHoryYBL2Ih8++77FCIZwEd9MDcYRLvyxeM0pVlj4BONr3x+BmJ0o8DDl9q4syxvhnyGRfo4KX6DUnOT4c56lKBsIzkiK/fIrtL2DrBXUATxxpMHkF2CXxRIBJ9YpMW4aqICM02biEdhP+Rm2HOot4Vl2VPgUxtB5C/Kj1UkaeSe4BA1iw04hpRrMXSc05+rBCxF8AYBrCxXOco3XJEY+1I2zJOkx2ND6bBJ2af0HLtYcKd80+N3YaGYdmr2YoFgW8BOqDutHqvnTDBVL+9Y9rQr44bj8IsnJqEiurVB7uRbTmWMJkNP+FYIsvhU6otxdNmD5kz7fC2XrOy/W8cvfUu7sLYhzHFq/3qfRs14j03VYHjqb7/0OwsksqTe5QyJVGN+BnSyhWv6m7V6u8xQEQMxZXKyhK6PX5isaIdT57roQe37B0OKui+pWzJ6DSjiKOCCMp1koQTKGz09RPS3xi38yYzrhiclCtBQ1DdCvEJutEmevAmrArPSD2HEZpsLCxDBD/xN4x0bJQQdgSZLw2rEM7B7MtYOKQwlmvf091Ee4F0jpiXNNAD+9MkQl1a2ub/uVux1/4UwmEbwRryK308=
  true:
    tags: true
    distributions: sdist bdist_wheel
repo: Sebokolodi/pyddi
